### ISSUE TITLE
"The extension manifest is invalid" when installing

### ISSUE THREAD

**Issue by lightswitchr** [tunnelvisionlabs/MouseNavigation#19]
Unable to install due to an error: "The extension manifest is invalid."

![image](https://cloud.githubusercontent.com/assets/7480500/22422285/7a15bbd4-e6e3-11e6-9ad7-760e390353f5.png)

Visual Studio 2012 installed.

**Comment by sharwell** [comment]
Thank you and sorry for this trouble. I'm looking into the issue!

**Comment by sharwell** [comment]
@lightswitchr I haven't had the chance to try this out, but another person online said they successfully installed the extension in Visual Studio 2012. Can you let me know what version/edition/update of Visual Studio you have, and also describe the steps you took to try and install it? It may save us some time getting it fixed. Thanks so much! :smile:

**Comment by lightswitchr** [comment]
Hi, I apologise for wasting your time. I mistakenly thought I had 2012 installed, I actually have 2010, which is a shame. Unfortunately I cannot upgrade due to company licensing. 

Many thanks anyway, and again I apologise profusely.

**Comment by sharwell** [comment]
@lightswitchr that's no problem. You'll find a 2010 compatible VSIX attached to one of the older releases on the release notes here on GitHub.
