### ISSUE TITLE
Cannot install for VS2013 if VS2015 is installed?

### ISSUE THREAD

**Issue by exsypher** [tunnelvisionlabs/MouseNavigation#21]
I have both 2013 and 2015 installed, but can only select 2015 in the installation. Is that a bug or my fault somehow

**Comment by sharwell** [comment]
What version of 2013 do you have installed?

**Comment by exsypher** [comment]
I see, never mind then, I have Express. Maybe I just switch to community

**Comment by sharwell** [comment]
@exsypher I haven't used Express or Community much myself, but from what I hear from other users, people are quite happy with Community Edition as long as they meet the licensing requirements (e.g. not using it for business purposes at companies over a certain size, etc. etc.).
