### ISSUE TITLE
Windows 10, Visual Studio 14, Logitech M570

### ISSUE THREAD

**Issue by kwalker360** [tunnelvisionlabs/MouseNavigation#7]
I just installed Mouse Navigation and it is not working with this configuration:

Windows 10
Visual Studio 14 (2015) Community Edition
Logitech M570 trackball

This is a new computer. Previously on a different laptop, I was using Windows 7 with the same Visual Studio and trackball and Mouse Navigation worked there.

Thanks,
Ken

**Comment by brittonbeckham** [comment]
I just installed this (same setup, Windows 10, VS 2014 Pro, Logitech M705) -- mouse buttons do nothing

**Comment by sharwell** [comment]
I'll mark this one as a duplicate of #5 :smile:

**Comment by kwalker360** [comment]
Per the discussion in #5 , I uninstalled SetPoint and the buttons are now working in my Visual Studio 2015. Thanks!
